version: 2
jobs:
  build:
    working_directory: ~/oice-web
    docker:
      - image: node:6-alpine
    steps:
      - run: apk add --no-cache curl git gzip tar
      - checkout
      - run: git submodule sync && git submodule update --init;
      - restore_cache:
          key: oice-web-{{ checksum "package.json" }}
      - run:
          name: Dependencies
          command: |
            mv src/common/constants/key.example.js src/common/constants/key.js
            yarn
      - run:
          name: Build
          command: yarn run build
      - run:
          name: Start Test
          command: yarn run server
          background: true
      - run:
          name: Curl Test
          command: |
            sleep 5
            curl --retry 10 --retry-delay 5 -v http://localhost:3000/
      - run:
          name: Lint Test
          command: yarn run lint
      - save_cache:
          key: oice-web-{{ checksum "package.json" }}
          paths:
            - "~/.cache/yarn"

